services:
  resource-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${RESOURCE_DB}
      POSTGRES_USER: ${RESOURCE_DB_USERNAME}
      POSTGRES_PASSWORD: ${RESOURCE_DB_PASSWORD}
    volumes:
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${RESOURCE_DB_PORT}:${DB_DEFAULT_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${RESOURCE_DB}" ]
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  song-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${SONG_DB}
      POSTGRES_USER: ${SONG_DB_USERNAME}
      POSTGRES_PASSWORD: ${SONG_DB_PASSWORD}
    volumes:
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${SONG_DB_PORT}:${DB_DEFAULT_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${SONG_DB}" ]
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  storage-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${STORAGE_DB}
      POSTGRES_USER: ${STORAGE_DB_USERNAME}
      POSTGRES_PASSWORD: ${STORAGE_DB_PASSWORD}
    volumes:
      - ./init-scripts/storage-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${STORAGE_DB_PORT}:${DB_DEFAULT_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${STORAGE_DB}" ]
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  service-registry:
    build:
      context: ./service-registry
    environment:
      APPLICATION_NAME: ${SERVICE_REGISTRY_APPLICATION_NAME}
      PORT: ${SERVICE_REGISTRY_PORT}
    ports:
      - "${SERVICE_REGISTRY_PORT}:${SERVICE_REGISTRY_PORT}"
    volumes:
      - "./logs:/app/logs"
    healthcheck:
      test: "curl --fail --silent localhost:${SERVICE_REGISTRY_PORT}/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  resource-service:
    build:
      context: ./resource-service
    environment:
      APPLICATION_NAME: ${RESOURCE_SERVICE_APPLICATION_NAME}
      PORT: ${RESOURCE_SERVICE_PORT}
      SERVICE_REGISTRY_HOST: ${SERVICE_REGISTRY_APPLICATION_NAME}
      SERVICE_REGISTRY_PORT: ${SERVICE_REGISTRY_PORT}
      DB_URL: resource-db
      DB_PORT: ${DB_DEFAULT_PORT}
      DB_USERNAME: ${RESOURCE_DB_USERNAME}
      DB_PASSWORD: ${RESOURCE_DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_URL: ${AWS_URL}
      STORAGE_SERVICE_URL: ${STORAGE_SERVICE_APPLICATION_NAME}
      STORAGE_SERVICE_PORT: ${STORAGE_SERVICE_PORT}
      RABBITMQ_HOST: ${MESSAGE_SERVICE_APPLICATION_NAME}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_AMQP_PORT}
      RESOURCE_PROCESSING_QUEUE: ${RESOURCE_PROCESSING_QUEUE}
    volumes:
      - "./logs:/app/logs"
    depends_on:
      resource-db:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      storage-service:
        condition: service_healthy
      message-service:
        condition: service_healthy
    ports:
      - "${RESOURCE_SERVICE_PORT}:${RESOURCE_SERVICE_PORT}"
    healthcheck:
      test: "curl --fail --silent localhost:${RESOURCE_SERVICE_PORT}/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  resource-processor:
    build:
      context: ./resource-processor
    environment:
      APPLICATION_NAME: ${RESOURCE_PROCESSOR_APPLICATION_NAME}
      PORT: ${RESOURCE_PROCESSOR_PORT}
      SERVICE_REGISTRY_HOST: ${SERVICE_REGISTRY_APPLICATION_NAME}
      SERVICE_REGISTRY_PORT: ${SERVICE_REGISTRY_PORT}
      RABBITMQ_HOST: ${MESSAGE_SERVICE_APPLICATION_NAME}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_PORT: ${RABBITMQ_AMQP_PORT}
      RESOURCE_PROCESSING_QUEUE: ${RESOURCE_PROCESSING_QUEUE}
      RESOURCE_PROCESSED_QUEUE: ${RESOURCE_PROCESSED_QUEUE}
      RESOURCE_SERVICE_HOST: ${RESOURCE_SERVICE_APPLICATION_NAME}
      SONG_SERVICE_HOST: ${SONG_SERVICE_APPLICATION_NAME}
    volumes:
      - "./logs:/app/logs"
    depends_on:
      service-registry:
        condition: service_healthy
      song-service:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:${RESOURCE_PROCESSOR_PORT}/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  song-service:
    build:
      context: ./song-service
    environment:
      APPLICATION_NAME: ${SONG_SERVICE_APPLICATION_NAME}
      PORT: ${SONG_SERVICE_PORT}
      SERVICE_REGISTRY_HOST: ${SERVICE_REGISTRY_APPLICATION_NAME}
      SERVICE_REGISTRY_PORT: ${SERVICE_REGISTRY_PORT}
      DB_URL: song-db
      DB_PORT: ${DB_DEFAULT_PORT}
      DB_USERNAME: ${SONG_DB_USERNAME}
      DB_PASSWORD: ${SONG_DB_PASSWORD}
    volumes:
      - "./logs:/app/logs"
    #    deploy:
    #      replicas: 2
    depends_on:
      song-db:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    ports:
      - "${SONG_SERVICE_OUT_PORT_RANGE}:${SONG_SERVICE_PORT}"
    healthcheck:
      test: "curl --fail --silent localhost:${SONG_SERVICE_PORT}/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  storage-service:
    build:
      context: ./storage-service
    environment:
      APPLICATION_NAME: ${STORAGE_SERVICE_APPLICATION_NAME}
      PORT: ${STORAGE_SERVICE_PORT}
      SERVICE_REGISTRY_HOST: ${SERVICE_REGISTRY_APPLICATION_NAME}
      SERVICE_REGISTRY_PORT: ${SERVICE_REGISTRY_PORT}
      DB_URL: storage-db
      DB_PORT: ${DB_DEFAULT_PORT}
      DB_USERNAME: ${STORAGE_DB_USERNAME}
      DB_PASSWORD: ${STORAGE_DB_PASSWORD}
    volumes:
      - "./logs:/app/logs"
    depends_on:
      storage-db:
        condition: service_healthy
      localstack:
        condition: service_healthy
      service-registry:
        condition: service_healthy
    ports:
      - "${STORAGE_SERVICE_PORT}:${STORAGE_SERVICE_PORT}"
    healthcheck:
      test: "curl --fail --silent localhost:${STORAGE_SERVICE_PORT}/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  message-service:
    image: rabbitmq:4.0.7-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}"
      - "${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./init-scripts/localstack/s3:/etc/localstack/init/ready.d"
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "${LOCALSTACK_PORT}:${LOCALSTACK_PORT}"
    healthcheck:
      test: "curl --fail --silent localhost:${LOCALSTACK_PORT}/_localstack/health | grep running || exit 1"
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  gateway-service:
    build:
      context: ./gateway-service
    environment:
      APPLICATION_NAME: ${GATEWAY_SERVICE_APPLICATION_NAME}
      PORT: ${GATEWAY_SERVICE_PORT}
      RESOURCE_SERVICE_HOST: ${RESOURCE_SERVICE_APPLICATION_NAME}
      SONG_SERVICE_HOST: ${SONG_SERVICE_APPLICATION_NAME}
      SERVICE_REGISTRY_HOST: ${SERVICE_REGISTRY_APPLICATION_NAME}
      SERVICE_REGISTRY_PORT: ${SERVICE_REGISTRY_PORT}
    volumes:
      - "./logs:/app/logs"
    depends_on:
      service-registry:
        condition: service_healthy
    ports:
      - "${GATEWAY_SERVICE_PORT}:${GATEWAY_SERVICE_PORT}"
    healthcheck:
      test: "curl --fail --silent localhost:${GATEWAY_SERVICE_PORT}/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  prometheus0:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"

  grafana0:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"

  elasticsearch0:
    image: elasticsearch:8.18.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./elastic:/usr/share/elasticsearch/data"
    ports:
      - "${ELASTICSEARCH_PORT_1}:${ELASTICSEARCH_PORT_1}"
      - "${ELASTICSEARCH_PORT_2}:${ELASTICSEARCH_PORT_2}"
    healthcheck:
      test: "curl --fail --silent localhost:9200/_cluster/health || exit 1"
      interval: 20s
      timeout: 120s
      retries: 5
      start_period: 10s

  logstash0:
    image: logstash:8.18.0
    environment:
      discovery.seed_hosts: logstash0
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - "./logstash/pipeline/logstash-nginx.config:/usr/share/logstash/pipeline/logstash-nginx.config"
      - "./logs:/home/logs/"
    depends_on:
      elasticsearch0:
        condition: service_healthy
    ports:
      - "${LOGSTASH_PORT_1}:${LOGSTASH_PORT_1}/tcp"
      - "${LOGSTASH_PORT_1}:${LOGSTASH_PORT_1}/udp"
      - "${LOGSTASH_PORT_2}:${LOGSTASH_PORT_2}"
      - "${LOGSTASH_PORT_3}:${LOGSTASH_PORT_3}"

  kibana0:
    image: kibana:8.18.0
    environment:
      SERVER_SSL_ENABLED: false
      ELASTICSEARCH_SSL_VERIFICATIONMODE: none
      ELASTICSEARCH_HOSTS: http://elasticsearch0:9200
    depends_on:
      elasticsearch0:
        condition: service_healthy
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"