DROP TABLE IF EXISTS resources CASCADE;

DROP SEQUENCE IF EXISTS resources_seq;

CREATE SEQUENCE IF NOT EXISTS resources_seq
START WITH 1
INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS resources (
	id INTEGER NOT NULL PRIMARY KEY,
    s3Bucket VARCHAR NOT NULL,
    key VARCHAR NOT NULL
);